(load "binarydiagnostic/main.lisp")
(load "dive/main.lisp")
(load "giantsquid/main.lisp")
(load "hydrothermalventure/main.lisp")
(load "lanternfish/main.lisp")
(load "sonarsweep/main.lisp")
(load "thetreacheryofwhales/main.lisp")
(defpackage :main
  (:use :cl)
  (:import-from binarydiagnostic :run-binarydiagnostic)
  (:import-from dive :run-dive)
  (:import-from giantsquid :run-giantsquid)
  (:import-from hydrothermalventure :run-hydrothermalventure)
  (:import-from lanternfish :run-lanternfish)
  (:import-from sonarsweep :run-sonar-sweep)
  (:import-from thetreacheryofwhales :run-thetreacheryofwhales)
)
(in-package :main)

(defun newlines ()
  (format t "~%~%")
)

(time (progn
  (time (run-sonar-sweep))
  (newlines)
  (time (run-dive))
  (newlines)
  (time (run-binarydiagnostic))
  (newlines)
  (time (run-giantsquid))
  (newlines)
  (time (run-hydrothermalventure))
  (newlines)
  (time (run-lanternfish))
  (newlines)
  (time (run-thetreacheryofwhales))
  (newlines)
))
